[project]
name = "workspace"
version = "1.0.0"
description = "Simple-Robotics projects workspace"
authors = ["Joris Vaillant <joris.vaillant@inria.fr>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]

[build-dependencies]
ccache = ">=4.10.1"
cmake = ">=3.10"
cxx-compiler = ">=1.7.0"
ninja = ">=1.12.1"
pkg-config = ">=0.29.2"
python = ">=3.8.0"
doxygen = "<1.9.7"

[feature.base.dependencies]
libboost-devel = ">=1.80.0"
libboost-python-devel = ">=1.80.0"
eigen = ">=3.3.0"
python = ">=3.8.0"
scipy = ">=1.10.0"
numpy = ">=1.22.0"

[feature.eigenpy.dependencies]
suitesparse = ">=5,<6"

[feature.coal.dependencies]
octomap = ">=1.9.8"
assimp = ">=5.4.2"
lxml = ">=5.2.2"
pylatexenc = ">=2.10"
qhull = ">=2020.2"
qhull-static = ">=2020.2"
llvm-openmp = ">=18.1.8"

[feature.coal-standalone.dependencies]
eigenpy = "*"

[feature.pinocchio.dependencies]
urdfdom = ">=4.0.0"
llvm-openmp = ">=18.1.8"
meshcat-python = ">=0.3.2"
casadi = ">=3.6.5"
cppad = ">=20230000"
cppadcodegen = ">=2.4.3"
matplotlib = ">=3.9.1"
mpfr = ">=4.2.1"
qhull = ">=2020.2"
qhull-static = ">=2020.2"

[feature.pinocchio-standalone.dependencies]
eigenpy = "*"
coal = "*"
pycppad = "*"

[feature.pycppad.dependencies]
cppad = ">=20230000"
cppadcodegen = ">=2.4.3"

[feature.pycppad-standalone.dependencies]
eigenpy = "*"

[feature.proxsuite.dependencies]
simde = ">=0.8.2"
libmatio = ">=1.5.27"

[feature.proxsuite-nlp.dependencies]
pytest = ">=8.2.2"
benchmark = ">=1.8.4"
fmt = ">=10.0"

[feature.proxsuite-nlp-standalone.dependencies]
eigenpy = "*"
pinocchio = "*"
example-robot-data = ">=4.1.0"
proxsuite = "*"

[feature.aligator.dependencies]
suitesparse = ">=5"
pytest = ">=8.2.2"
benchmark = ">=1.8.4"
fmt = ">=10.0"
matplotlib = ">=3.9.1"
llvm-openmp = ">=18.1.8"
# crocoddyl = ">=2.1.0"

[feature.aligator-standalone.dependencies]
eigenpy = "*"
pinocchio = "*"
proxsuite-nlp = "*"
example-robot-data = ">=4.1.0"

[feature.loik.dependencies]

[feature.loik-standalone.dependencies]
pinocchio = "*"
example-robot-data = ">=4.1.0"

[environments]
all = { features = [
  "base",
  "eigenpy",
  "coal",
  "pinocchio",
  "pycppad",
  "proxsuite",
  "proxsuite-nlp",
  "aligator",
  "loik",
] }
eigenpy-standalone = { features = ["base", "eigenpy"] }
coal-standalone = { features = ["base", "coal", "coal-standalone"] }
pinocchio-standalone = { features = [
  "base",
  "pinocchio",
  "pinocchio-standalone",
] }
pycppad-standalone = { features = ["base", "pycppad", "pycppad-standalone"] }
proxsuite-standalone = { features = ["base", "proxsuite"] }
proxsuite-nlp-standalone = { features = [
  "base",
  "proxsuite-nlp",
  "proxsuite-nlp-standalone",
] }
aligator-standalone = { features = ["base", "aligator", "aligator-standalone"] }
loik-standalone = { features = ["base", "loik", "loik-standalone"] }
simple-minimal = { features = ["base", "coal", "coal-standalone", "pinocchio"] }
