[project]
name = "workspace"
version = "1.0.0"
description = "Simple-Robotics projects workspace"
authors = ["Joris Vaillant <joris.vaillant@inria.fr>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]

[build-dependencies]
ccache = ">=4.10.1,<4.11"
cmake = ">=3.10"
cxx-compiler = ">=1.7.0,<1.8"
ninja = ">=1.12.1,<1.13"
pkg-config = ">=0.29.2,<0.30"
python = ">=3.8.0,<3.13"
doxygen = "<1.9.7"

[feature.base.dependencies]
boost = ">=1.80.0,<1.85"
eigen = ">=3.3.0,<3.5"
python = ">=3.8.0,<3.13"
scipy = ">=1.10.0,<1.15"
numpy = ">=1.22.0,<1.27"

[feature.eigenpy.dependencies]
suitesparse = ">=5,<6"

[feature.hpp-fcl.dependencies]
octomap = ">=1.9.8,<1.10"
assimp = ">=5.4.2,<5.5"
lxml = ">=5.2.2,<5.3"
pylatexenc = ">=2.10,<3"
qhull = ">=2020.2,<2021"
qhull-static = ">=2020.2,<2021"
llvm-openmp = ">=18.1.8,<18.2"

[feature.hpp-fcl-standalone.dependencies]
eigenpy = "*"

[feature.pinocchio.dependencies]
urdfdom = ">=4.0.0,<4.1"
llvm-openmp = ">=18.1.8,<18.2"
meshcat-python = ">=0.3.2,<0.4"
casadi = ">=3.6.5,<3.7"
cppad = "<=20230000"
cppadcodegen = ">=2.4.3,<2.5"
matplotlib = ">=3.9.1,<3.10"
mpfr = ">=4.2.1,<4.3"
qhull = ">=2020.2,<2021"
qhull-static = ">=2020.2,<2021"

[feature.pinocchio-standalone.dependencies]
eigenpy = "*"
hpp-fcl = "*"
pycppad = "*"

[feature.pycppad.dependencies]
cppad = "<=20230000"
cppadcodegen = ">=2.4.3,<2.5"

[feature.pycppad-standalone.dependencies]
eigenpy = "*"

[feature.proxsuite.dependencies]
simde = ">=0.8.2,<0.9"
libmatio = ">=1.5.27,<1.6"

[feature.proxsuite-nlp.dependencies]
pytest = ">=8.2.2,<8.3"
benchmark = ">=1.8.4,<1.9"
fmt = ">=10.0,<11.1"

[feature.proxsuite-nlp-standalone.dependencies]
eigenpy = "*"
pinocchio = "*"
example-robot-data = ">=4.1.0,<4.2"
proxsuite = "*"

[feature.aligator.dependencies]
suitesparse = ">=5,<6"
pytest = ">=8.2.2,<8.3"
benchmark = ">=1.8.4,<1.9"
fmt = ">=10.0,<11.1"
matplotlib = ">=3.9.1,<3.10"
llvm-openmp = ">=18.1.8,<18.2"
# crocoddyl = ">=2.1.0,<2.2"

[feature.aligator-standalone.dependencies]
eigenpy = "*"
pinocchio = "*"
proxsuite-nlp = "*"
example-robot-data = ">=4.1.0,<4.2"

[feature.loik.dependencies]

[feature.loik-standalone.dependencies]
pinocchio = "*"
example-robot-data = ">=4.1.0,<4.2"

[environments]
all = { features = [
  "base",
  "eigenpy",
  "hpp-fcl",
  "pinocchio",
  "pycppad",
  "proxsuite",
  "proxsuite-nlp",
  "aligator",
  "loik",
] }
eigenpy-standalone = { features = ["base", "eigenpy"] }
hpp-fcl-standalone = { features = ["base", "hpp-fcl", "hpp-fcl-standalone"] }
pinocchio-standalone = { features = [
  "base",
  "pinocchio",
  "pinocchio-standalone",
] }
pycppad-standalone = { features = ["base", "pycppad", "pycppad-standalone"] }
proxsuite-standalone = { features = ["base", "proxsuite"] }
proxsuite-nlp-standalone = { features = [
  "base",
  "proxsuite-nlp",
  "proxsuite-nlp-standalone",
] }
aligator-standalone = { features = ["base", "aligator", "aligator-standalone"] }
loik-standalone = { features = ["base", "loik", "loik-standalone"] }
